kafka_logger:
  bootstrap_servers:
    - 10.228.129.157:19092
    - 10.228.129.158:19092
    - 10.228.130.198:19092

  topic: orgjjt

  level: DEBUG

  kafka_extra:
    client_id: kafka-logger
    acks: 1
    retries: 3
    compression_type: lz4
    linger_ms: 10

  formatter:
    default_time_format: "%Y-%m-%d %H:%M:%S"
    default_msec_format: "%s.%03d"
    fields:
      - name: asctime
        rename: timestamp

      - name: levelname

      - name: name
        rename: loggername

      - name: threadName
        rename: threadname

      - name: module
        rename: modulename

      - name: lineno

      - name: message

      - name: exc_info
        rename: stacktrace

      - name: host
        static_factory: builtin:get_host_ip

      - name: traceid
        dynamic_factory: builtin:get_trace_id

      - name: appname
        static: my-app

      - name: env
        static: dev
